# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d141436f7a45d1d74fb12510fd8de09ff1eff762989501067a8c6c6b85fdbd16dd8bcdc0aadd43f6eef571c21a2efcdd6e5968f1afbf89313979274ca6557a82

test:
  secret_key_base: 32ea7131f05dadd12bf8326174b99058df1426614e25b7652b67fb5e20d337b987d54302162edd604f18d092f025f66f43858a2f2bfbc2c0cf93521b9f065f2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
